#make valgrind ARGS="-d /home/brighton/media/manga/Tsubaki-chou_Lonely_Planet -o Tsubaki-chou_Lonely_Planet.cbz"
#make run ARGS="-v -c -f /home/brighton/media/manga/Tsubaki-chou_Lonely_Planet/[0001]_Chapter_1.cbz -o Tsubaki-chou_Lonely_Planet.cbz"
make run ARGS="-f /home/brighton/media/manga/Tsubaki-chou_Lonely_Planet/[0001]_Chapter_1.cbz -o Tsubaki-chou_Lonely_Planet.pdf"
#make run ARGS="-f /home/brighton/media/manga/Vinland_Saga/[0001]_Chapter_1_Normanni.cbz -o vinland.pdf"
#make valgrind ARGS="-d /home/brighton/media/manga/Tsubaki-chou_Lonely_Planet -o Tsubaki-chou_Lonely_Planet.pdf"
#make run ARGS="-v -c -f ./t[01].cbz -o Tsubaki-chou_Lonely_Planet.pdf"
#make gdb ARGS="-v -c -f ./t[01].cbz -o Tsubaki-chou_Lonely_Planet.pdf"
